steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - -c
      - |
        on_going_build=($(gcloud builds list --ongoing --format='value(id)' --filter="substitutions._TRIGGER_ID=$_TRIGGER_ID" | xargs))
        for (( i=0; i<${#on_going_build[@]}; i++ )); do
          if [ "$i" -gt "0" ]; then # skip current
            echo "Cancelling build ${on_going_build[i]}"
            gcloud builds cancel --no-user-output-enabled ${on_going_build[i]}
          fi
        done
    id: "Cancel ongoing builds"
    entrypoint: 'bash'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--build-arg=GITHUB_USERNAME=$_GITHUB_USERNAME'
      - '--build-arg=GITHUB_TOKEN=$_GITHUB_TOKEN'
      - .
      - '-f'
      - Dockerfile
    id: "Push to github maven repository"
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  machineType: UNSPECIFIED
  substitutionOption: ALLOW_LOOSE
timeout: "7200s"